stages:
  - test
  - deploy

rust-latest-test:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose

rust-nightly-test:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test --verbose

pages:
  stage: deploy
  image: rustlang/rust:nightly
  script:
    - cargo run --bin sc_server -- --only-docs
    - mkdir -p public/
    - rm -rf public/*
    - cp -r target/sl_docs/* public/
  artifacts:
    paths:
    - public
