stages:
  - test
  - deploy

# rust-latest-test:
#   stage: test
#   image: rust:latest
#   script:
#     - cargo test --verbose
#
# rust-nightly-test:
#   stage: test
#   image: rustlang/rust:nightly
#   script:
#     - cargo test --verbose

pages:
  stage: deploy
  image: rustlang/rust:nightly
  script:
    - cargo run --bin sc_server -- --only-docs
    - mkdir -p public/
    - rm -rf public/*
    - cp -r target/sl_docs/* public/
  artifacts:
    paths:
    - public

coverage:
  image: "rustdocker/rust:nightly"
  stage: extras
  variables:
    RUSTFLAGS: "-Zinstrument-coverage"
    LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
  script:
    - rustup component add llvm-tools-preview
    - cargo test
      # generate html report
    - cargo install grcov
    - grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing --ignore "*cargo*" -o ./coverage/
  artifacts:
    paths:
      - 'coverage'
