stages:
  - test

rust-latest-test:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose

rust-nightly-test:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test --verbose