[workspace]
members = [
  "sc_macros",
  "sc_transfer",
  "sc_data",
  "sc_generated",
  "sc_common",
  "sc_server",
  "sc_proxy",
  "sc_cli",
]

# Using cargo flamegraph, this is needed.
# See more: https://github.com/flamegraph-rs/flamegraph
[profile.release]
debug = true

[profile.dev]
opt-level = 2
lto = false

[profile.bench]
opt-level = 2
