[workspace]
members = [
  "server",
  "proxy",
  "data",
  "generated",
  "sc_macros",
]

# Using cargo flamegraph, this is needed.
# See more: https://github.com/flamegraph-rs/flamegraph
[profile.release]
debug = true

[profile.dev]
opt-level = 2
lto = false

[profile.bench]
opt-level = 2
