[workspace]
members = [
  "server",
  "proxy",
  "data",
  "data-gen",
]

# Using cargo flamegraph, this is needed.
# See more: https://github.com/flamegraph-rs/flamegraph
[profile.release]
debug = true
