[package]
name = "bb_ffi"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-types = { version = "2.2.1", default-features = false, features = ["std"] }

[build-dependencies]
cbindgen = "0.20.0"
