# The default view distance. Note that this can be changed for a single
# player via a plugin at runtime.
view-distance: 10

# Configs for world generation/loading.
world:
  # If set, the world cannot be modified. This can be used in minigame
  # lobbies, for example.
  locked: false

  # Generation settings

  # Vanilla world loading settings
  vanilla:
    # If set, then the world will be a void world, and a vanilla world will
    # be loaded when the server starts. This loads first, so schematics will
    # replace any blocks set by the vanilla world.
    enabled: false
    # The path to the world. This should be a path to a world containing a
    # `chunks` folder, which should contain all of the chunks of the world.
    # The value of this path is ignored if vanilla loading is not enabled.
    path: ""

  # Schematic reading settings.
  schematic:
    # If set, then the world will be a void world, and a schematic will be
    # loaded from the given path on server startup. This overrides any of
    # the options below.
    enabled: false
    # The path to the schematic file. The value of this path is ignored
    # if schematic loading is not enabled.
    path: ""

  # If set, then the entire world will be filled with debug blocks.
  debug: false
  # If set, the whole world will be void.
  void: false
  # If not a debug world, and not a void world, then these are the biomes
  # that will be added to the terrain generation.
  biomes:
    - desert
    - forest
    - plains
    - mountains
