# Only show info logs by default.
log-level = "info"

# Don't log any packets. This is just for debugging. If you need to debug packets,
# you can add "all", which will log every packet. You can also add a specific packet
# name (such as "Flying"), which will only log packets with that name.
log-packets = []

# The address the server will listen for connections on. Vanilla clients
# cannot connect to this address! The proxy must be configured to connect
# to this address instead.
address = "0.0.0.0:8483"

# The default view distance. Note that this can be changed for a single
# player via a plugin at runtime.
view-distance = 10

# Whenever a player joins, they will be put into this gamemode. This can
# be overriden with plugins, but without any plugins, this will be the
# gamemode of all the clients.
#
# Can be one of:
# - creative
# - survival
# - adventure (partially implemented)
# - spectator (not implemented)
default-gamemode = "creative"

# The place where everyone spawns in within the world.
spawn-point = { x = 0.0, y = 64.0, z = 0.0 }

# If true, the world will search upwards from the given spawn point for a
# suitable location every time a player is spawned. If false, then the world
# will simply place new players at the spawn point (even if they suffocate).
find-spawn = true

# Configs for world generation/loading.
[world]
# If set, the world cannot be modified. This can be used in minigame
# lobbies, for example.
locked = false

# Generation settings

# If set, then the entire world will be filled with debug blocks.
debug = false
# If set, the whole world will be void.
void = false
# If not a debug world, and not a void world, then these are the biomes
# that will be added to the terrain generation.
biomes = ["desert", "forest", "plains", "mountains"]

# Vanilla world loading settings
[world.vanilla]
  # If set, then the world will be a void world, and a vanilla world will
  # be loaded when the server starts. This loads first, so schematics will
  # replace any blocks set by the vanilla world.
  enabled = false
  # The path to the world. This should be a path to a world containing a
  # `chunks` folder, which should contain all of the chunks of the world.
  # The value of this path is ignored if vanilla loading is not enabled.
  path = ""

# Schematic reading settings.
[world.schematic]
  # If set, then the world will be a void world, and a schematic will be
  # loaded from the given path on server startup. This overrides any of
  # the options below.
  enabled = false
  # The path to the schematic file. The value of this path is ignored
  # if schematic loading is not enabled.
  path = ""
